<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>markdown</string>
		<string>md</string>
		<string>pandoc</string>
		<string>mdown</string>
		<string>markdn</string>
	</array>
	<key>name</key>
	<string>SarahsPandocMarkdown</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.reference.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.address.markdown</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Image link references</string>
			<key>match</key>
			<string>!\[(.*?)\]\((.*?)\)</string>
			<key>name</key>
			<string>markup.image.markdown</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.reference.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.address.markdown</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Link references</string>
			<key>match</key>
			<string>\[(.*?)\](\((.*?)\))+</string>
			<key>name</key>
			<string>markup.link.markdown</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.notecall.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.inlinenote.text.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.notecall.markdown</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Inline note</string>
			<key>match</key>
			<string>(\^\[)(.*?)(\])</string>
			<key>name</key>
			<string>markup.inlinenote.markdown</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^\[\^.*?\]:)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.notecall.markdown</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Footnotes</string>
			<key>end</key>
			<string>^$</string>
			<key>name</key>
			<string>markup.footnote.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.*</string>
					<key>name</key>
					<string>markup.footnote.text.markdown</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Inline notecall</string>
			<key>match</key>
			<string>\[\^.*?\]</string>
			<key>name</key>
			<string>markup.notecall.markdown</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.metainfo.mark.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.metainfo.value.markdown</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Metainformation of the files such as Title, Author, Date</string>
			<key>match</key>
			<string>^(%)\s+(.*)</string>
			<key>name</key>
			<string>markup.metainfo.old.markdown</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^-{3}$</string>
			<key>comment</key>
			<string>YAML Block of Metadata</string>
			<key>end</key>
			<string>^[-.]{3}$</string>
			<key>name</key>
			<string>markup.metainfo.yaml.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.metainfo.variable.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.metainfo.mapping.markdown</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>markup.metainfo.value.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^([^:]+)(:)([^\n]*)$</string>
					<key>name</key>
					<string>markup.metainfo.yaml.text.markdown</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comments in HTML format</string>
			<key>match</key>
			<string>&lt;!--(.*?)--&gt;</string>
			<key>name</key>
			<string>markup.comment.markdown</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comments in HTML format -- Multiline</string>
			<key>begin</key>
			<string>&lt;!--</string>
			<key>end</key>
			<string>--&gt;</string>
			<key>name</key>
			<string>markup.comment.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.*?</string>
					<key>name</key>
					<string>markup.comment.text.markdown</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Heading</string>
			<key>match</key>
			<string>^(={3,})(?=[ 	]*$)</string>
			<key>name</key>
			<string>markup.heading.1.markdown</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Heading</string>
			<key>match</key>
			<string>^(-{3,})[ 	]*$</string>
			<key>name</key>
			<string>markup.heading.2.markdown</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Heading</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.heading.1.symbol.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.heading.1.text.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(#)( .+)</string>
			<key>name</key>
			<string>markup.heading.1.markdown</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Heading</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.heading.2.symbol.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.heading.2.text.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(#{2})( .+)</string>
			<key>name</key>
			<string>markup.heading.2.markdown</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Heading</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.heading.symbol.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.heading.text.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(#+)( .+)</string>
			<key>name</key>
			<string>markup.heading.markdown</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Bold</string>
			<key>match</key>
			<string>\*\*(.)+\*\*</string>
			<key>name</key>
			<string>punctuation.definition.bold.markdown</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Inline code</string>
			<key>match</key>
			<string>`(.)+`</string>
			<key>name</key>
			<string>markup.inlinecode.markdown</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Italic</string>
			<key>match</key>
			<string>(^\*[^ ][^*]*\*)|([^\n]\*[^*^\n]+\*)</string>
			<key>name</key>
			<string>punctuation.definition.italic.markdown</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Math LaTeX</string>
			<key>begin</key>
			<string>\$</string>
			<key>end</key>
			<string>\$</string>
			<key>name</key>
			<string>math.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[0-9]+</string>
					<key>name</key>
					<string>math.markdown.number</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[^{^_^\^^\s^$]+</string>
					<key>name</key>
					<string>math.markdown.key</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[\[\]{}()]</string>
					<key>name</key>
					<string>math.markdown.braces</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[_\^]\{[^}]+\}</string>
					<key>name</key>
					<string>math.markdown.expind</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>comment</key>
			<string>Reference citation</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>citation.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[A-Za-z0-9_éèàçïüôê]+</string>
					<key>name</key>
					<string>citation.referencekey.markdown</string>
				</dict>
				<dict>
					<key>match</key>
					<string>@</string>
					<key>name</key>
					<string>citation.symbol.markdown</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>citation.symbol.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>citation.referencekey.markdown</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Reference citation</string>
			<key>match</key>
			<string>(@)([A-Za-z0-9_]+)</string>
			<key>name</key>
			<string>citation.inline.markdown</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>List</string>
			<key>match</key>
			<string>^ ?([-*] |\d+[.\-)])</string>
			<key>name</key>
			<string>markup.list</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>List2</string>
			<key>match</key>
			<string>^  +([-*] |\d+[.\-)])</string>
			<key>name</key>
			<string>markup.list.2</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Blockquote text</string>
			<key>match</key>
			<string>^&gt;\s*(.*)</string>
			<key>name</key>
			<string>quote.markdown</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Code</string>
			<key>match</key>
			<string>^    +[^\n]+</string>
			<key>name</key>
			<string>markup.code</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;</string>
			<key>end</key>
			<string>&gt;</string>
			<key>name</key>
			<string>balise.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\w+</string>
					<key>name</key>
					<string>balise.markdown</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Balise text</string>
			<key>match</key>
			<string>".+?"</string>
			<key>name</key>
			<string>string</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.markdown</string>
	<key>uuid</key>
	<string>50a29d70-cec4-4462-ad8a-8f44715cb391</string>
</dict>
</plist>